### ISSUE TITLE
Consolidate example files/folders

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/druid-operator#156]
There are currently three directories with multiple files that together (as far as I can tell) make up a single example.

I'd like each file in the examples folder to be useful on its own which means it should include everything that's needed including a comment at the top detailing what's happening in this file for a new user.
This makes it easy for people to get started by issuing a command like `kubectl apply -f https://github.com/stackabletech/.....`

I'm fine with keeping three directories but I'm also fine with getting rid of the directories.

But each example should contain the ZK cluster definition as well as a Znode and use said Znode configmap instead of the ZooKeeper wide configmap

**Comment by maltesander** [comment]
The Zookeeper cluster examples are outdated too. (ports and datadir still provided)
