### ISSUE TITLE
Configure Druid to support S3

### ISSUE THREAD

**Issue by stefanigel** [stackabletech/druid-operator#2]
See Druid documentation
https://druid.apache.org/docs/latest/ingestion/native-batch.html#s3-input-source

Acceptance Criteria
- [x] Druid is configured to use S3 as Input Source for data (by Stackable Druid Operator)
- [x] Druid is configured to use S3 as deep staorage (by Stackable Druid Operator)
- [x] A User may load data stored in S3 into Druid
- [x] A User may query these data, at least via REST call:  curl -X POST '<queryable_host>:<port>/druid/v2/?pretty' -H 'Content-Type:application/json' -H 'Accept:application/json' -d @<query_json_file>

**Comment by fhennig** [comment]
I've started working on deep storage in S3

**Comment by fhennig** [comment]
Ready for review

**Comment by fhennig** [comment]
PR was accepted; done!
