### ISSUE TITLE
Handle stale information/clean up stale resources

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/druid-operator#207]
Currently our operators will not act on removed information from the CR in some/most/all cases.

One example:
HBase operator has three roles (master, regionServer, restServer). If I create a HBase server CR with a restServer component and then remove it later (entirely, not setting replicas to 0) our operator will not clean up the STS that belongs to this role.

## Proposed solution

Use the `ClusterResource` struct from operator-rs to manage Kubernetes resources belonging to a Cluster object. An example of its usage can be found in the Superset Operator: https://github.com/stackabletech/superset-operator/blob/main/rust/operator-binary/src/superset_controller.rs#L241

## Acceptance criteria

- [ ] This is done when all stale Kubernetes resources are cleaned up. A resource becomes stale when it's not part of the current cluster definition anymore.
- [ ] `ZNode` and `S3Connection` resources are not deleted because the operator cannot know if they are stale or not.
- [ ] There is at least one test.
- [ ] Documentation on operator implementation is updated with information regarding handling of stale resources.
- [ ] Upgrade to the latest version of` operator-rs` (`0.25` at the moment).

NOTE: This is part of an epic (https://github.com/stackabletech/issues/issues/203) and _might_ not apply to this operator. If that is the case please comment on this issue and just close it. This issue was created as part of a special bulk creation operation.

**Comment by fhennig** [comment]
Does this also apply to removing i.e. an S3 connection for ingestion? Updating this would probably require restarting Druid.

**Comment by soenkeliebau** [comment]
@fhennig none of the checkboxes are ticked I have looked througth things and can probably guess most of them, but am unsure for some of them.

**Comment by fhennig** [comment]
Nothing was done to the documentation, there is no good place to document this yet. We need a general description of how the operator manges resources, and it was decided to postpone this to this indefined later time in the future.
