### ISSUE TITLE
Integration-tests relocation and improved stability

### ISSUE THREAD

**Issue by adwk67** [stackabletech/druid-operator#235]
As a user I want to have the druid integration tests moved to the operator repository and for the stability to be improved (e.g. currently the python tests start before the druid components are reachable).

**Comment by fhennig** [comment]
I want to add to this that we should make the healthcheck script nicer, it throws so many errors and it makes the test log very hard to read

**Comment by fhennig** [comment]
@adwk67 I'm closing this, as the tests have been relocated to this repository and are stable. They can be optimized, but they are stable. If you disagree, feel free to reopen this
