### ISSUE TITLE
Properly support S3 structs

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/druid-operator#252]
When implementing support for S3 in the operators out there we took some shortcuts like ignoring `accessStyle` and `tls` settings for now. We need to honor them and not just silently ignore them.

What needs to be done is described in https://github.com/stackabletech/issues/issues/226

**Comment by fhennig** [comment]
`accessStyle` has already been implemented by Sebastian, now `tls` is missing.

Setting `https` for the `druid.s3.protocol` should enable HTTPS/TLS for connecting to s3 ([docs](https://druid.apache.org/docs/latest/development/extensions-core/s3.html)).

A custom CA cert for the s3 instance looks a bit tricky, the s3 docs don't mention anything like that. On the TLS docs site there's a section [Custom Certificate Checks](https://druid.apache.org/docs/latest/operations/tls-support.html#custom-certificate-checks). An extension allows to supply custom certificates to be checked, but I am unsure whether these are also used for the s3 connection, or just for inter-process communication.
