### ISSUE TITLE
Implement resource requests and limits for Druid pods

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/druid-operator#277]
Part of this epic https://github.com/stackabletech/issues/issues/241

### Acceptance criteria

- [x] Resource requests and limits are configurable in CRD using the [common structs](https://github.com/stackabletech/operator-rs/blob/e56110dd394c98a67f21ff17f7fab6c88f3aa322/src/commons/resources.rs#L77) from operator-rs
- [x] Resource requests and limits are configured for Kubernetes pods
- [x] Resource requests and limits are configured in the product (e.g. "-Xmx" etc. for Java based images)
- [x] Adapt/Add integration tests to specify and test correct amount of resources
- [x] Adapt/Add examples
- [x] Adapt documentation: New section in `usage.adoc` with product specific information and link to common shared resources concept
- [x] Optional: Use sensible defaults for each role (if reasonable and applicable) and document accordingly in `usage.adoc`
- [x] Code contains useful comments
- [x] Changelog updated
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
- [x] Helm chart can be installed and deployed operator works (or not applicable)
- [ ] Feature Tracker has been updated
- [ ] Followup tickets have been created if needed (e.g. to update demos)

Relevant part of the code: https://github.com/stackabletech/druid-operator/blob/129c5e9769f513c9a9f318392f6b508b2a1f2a81/rust/operator-binary/src/config.rs
There are the jvm settings already in there, should be factored out somewhere

**Comment by soenkeliebau** [comment]
Looks good to me. Checked the docs, Changelog and the feature tracker.

**Comment by soenkeliebau** [comment]
After checking back on this with Malte I updated the feature tracker to show this is part of the upcoming release 22/11 
@lfrancke just in case since this is a young process, if you want to keep up to date with changes in the feature tracker.

**Comment by sbernauer** [comment]
22/11 is the correct one, yes
