### ISSUE TITLE
Druid Authentication

### ISSUE THREAD

**Issue by stefanigel** [stackabletech/druid-operator#3]
As an analyst I want to log in into Druid having READ or WRITE Access
https://druid.apache.org/docs/latest/operations/security-overview.html
https://druid.apache.org/docs/latest/operations/security-user-auth.html

**Acceptance Criteria:** 
- [ ] Configuring Authentication is supported by Druid Operator
- [ ] at least 1 auth method is supported

**Comment by lfrancke** [comment]
I've decided to close this in favor of the more specific https://github.com/stackabletech/druid-operator/issues/144
