### ISSUE TITLE
Investgate integration test instability

### ISSUE THREAD

**Issue by razvan** [stackabletech/druid-operator#303]
## Description

Part of: https://github.com/stackabletech/t2/issues/368.

In this ticket we generate the kuttl tests once and re-run them 20 times against a single GKE Kubernetes cluster.

## Protocol

**15.09.22** Installed release 22.09  operator and nightly tests. This failed because of version mismatch but K3s cluster was bust after the third pass.

On GKE the following error was encountered:

`Pod "druid-resources-middlemanager-resources-from-role-group-0" is invalid: metadata.labels: Invalid value: "druid-resources-middlemanager-resources-from-role-group-5bd6db4495": must be no more than 63 characters 
`

**16.09.22** Cleanup and started the release tests against a GKE cluster.

**Comment by soenkeliebau** [comment]
@razvan and I did some testing today with the following scenarios (all versions were release 22.09 versions):

### Druid Operator Integration Tests 
GKE: no failure in about 10 runs
Ionos: 1 failure - 7 succeeded  

For the failure on Ionos the following was found in the log:

```
    logger.go:42: 16:51:32 | ingestion-no-s3-ext_druid-0.22.1-authorizer0.1.0-stackable0.2.0_zookeeper-3.8.0-stackable0.7.1_hadoop-3.2.2-stackable0.5.0/5-ingestioncheck | test step failed 5-ingestioncheck
    case.go:361: failed in step 5-ingestioncheck
    case.go:363: command "" exceeded 19 sec timeout, context deadline exceeded
```

Which migth bear investigation, if there actually is a 19 second timeout that might actually cause some flakiness.That being said, this step never failed in our nighly tests in recorded history..

### Kafka Operator Integration Tests
GKE: 1 failure  4 successes


Overall it looks like stability of the tests is much improved when running against a persistent (may not be a factor here though) managed k8s cluster, certainly for GKE, Ionos as well, but to a lesser degree.

**Comment by razvan** [comment]
The decision was made to stop work here and close this ticket. The next step is to run the nightly tests against managed k8s instead of k3s only.

**Comment by soenkeliebau** [comment]
Further activities around test stability will be tracked in https://github.com/stackabletech/t2/issues/368
