### ISSUE TITLE
Don't use derby for metadata storage as a default

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/druid-operator#309]
While improving demos I had a Druid instance running for 3-4 days on Ionos k8s. Suddenly everything (all datasources, ingestion tasks etc) were gone. The k8s has restarted all Pods - i assume a maintenance window. I had a look and after looking at https://druid.apache.org/docs/latest/dependencies/metadata-storage.html i think all the data is still on S3 but the metadata is lost.
I think we should prevent users from running into the same problem. I can make the demo resilient by putting a Postgres below, but i think we should address this at the druid-operator level already.
Like

- [x] All the examples (also in docs) use a postgres as metadata storage
- [ ] All the demos using Druid use a postgres as metadata storage
- [x] Make a decision if users even should have the possibility to configure a derby instance or not. Implement accordingly => They do and that's ok. Everything is fine. I'm stupid

**Comment by lfrancke** [comment]
Can you elaborate what you mean with:

> but i think we should address this at the druid-operator level already.

Is this related to

>  Make a decision if users even should have the possibility to configure a derby instance or not. Implement accordingly

?

**Comment by soenkeliebau** [comment]
As a light-weight alternative, we could look into mounting a PVC for the derbe storage to make this persistent across restarts.

**Comment by sbernauer** [comment]
> I can make the demo resilient by putting a Postgres below, but i think we should address this at the druid-operator level already.

I can easily fix this by fixing the demo but i fear if i do so all users will use the druid examples and run into the exact same issue.
So i propose to change the examples (maybe the operator defaults as well)

**Comment by lfrancke** [comment]
I'm not sure if this ticket is ready to work on?
As far as I understand Postgres is already possible in Druid and this is only about changing the demos to use it?

**Comment by lfrancke** [comment]
Thank you!
