### ISSUE TITLE
Historicals won't start when setting memory limit

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/druid-operator#359]
### Affected version

0.8.0

### Current and expected behavior

My historicals keep crashing because the liveness probe fails. Looking at the CPU and Memory I think they simply need more compute resources.
When setting something else than 2Gi (the default) of memory for the historicals, they wont start up:
`Error in custom provider, java.lang.OutOfMemoryError: Direct buffer memory`

### Possible solution

Not tested, just some ideas:
1. Set `druid.processing.numThreads` to cpu limit. Also add an option role/rolegroup config.numThreads that allows to overwrite this value -> I've set the numThreads to 1 and it didn't help. Also setting the numMergeBuffers to 1 didn't help
2. Somehow calculate `druid.processing.buffer.sizeBytes` and set it explicitly
3. Calculate "The amount of direct memory needed by Druid is at least druid.processing.buffer.sizeBytes * (druid.processing.numMergeBuffers + druid.processing.numThreads + 1)" and set that as `-XX:MaxDirectMemorySize=<direct memory>`
4. Set -Xmx to `<pod memory limit> * 0.8 (?) - <direct memory>`

Update: I went with (2) and calculated the sizeBytes myself. The default setting is just "auto" and we don't know what it's doing. Druid probably doesn't expect to be so memory constrained. Setting it manually makes us know all the variables involved.

- [ ] Load test done successfully. Demo [nifi-kafka-druid-water-level-data](https://docs.stackable.tech/stackablectl/stable/demos/nifi-kafka-druid-water-level-data.html) can be used

### Additional context

Full log [druid-historical-default-0.log](https://github.com/stackabletech/druid-operator/files/10225376/druid-historical-default-0.log)

With 2Gi mem limit (working config) we have
```
-Xms1638m                                                                                                                                                                                                     
-Xmx1638m                                                                                                                                                                                                     
-XX:MaxDirectMemorySize=400m
```

`druid.processing.numThreads ` => It defaults to max(num cores - 1, 1) => 1
`druid.processing.numMergeBuffers` => `max(2, druid.processing.numThreads / 4)` => 2
`druid.processing.buffer.sizeBytes` => IDK, auto with a max of 1GB 
direct memory `druid.processing.buffer.sizeBytes * (druid.processing.numMergeBuffers + druid.processing.numThreads + 1)` => 1GB * (2 + 1 +1) => 4GB
```
apiVersion: druid.stackable.tech/v1alpha1
kind: DruidCluster
metadata:
  name: druid
spec:
  version: 24.0.0-stackable0.1.0
  zookeeperConfigMapName: druid-znode
  metadataStorageDatabase:
    dbType: postgresql
    connString: jdbc:postgresql://postgresql-druid/druid
    host: postgresql-druid
    port: 5432
    user: druid
    password: XXX
  deepStorage:
    s3:
      bucket:
        inline:
          bucketName: druid
          connection:
            inline:
              host: minio-druid
              port: 9000
              accessStyle: Path
              credentials:
                secretClass: druid-s3-credentials
      baseKey: data
  brokers:
    roleGroups:
      default:
        replicas: 1
  coordinators:
    roleGroups:
      default:
        replicas: 1
  historicals:
    roleGroups:
      default:
        replicas: 2
        config:
          resources:
            cpu:
              min: "1"
              max: "2"
            memory:
              limit: 4Gi
        configOverrides:
          runtime.properties:
            # druid.processing.numThreads: "2"
            # Can be changed in 23.01, see https://github.com/stackabletech/druid-operator/pull/342
            druid.segmentCache.locations: '[{"path":"/stackable/var/druid/segment-cache","maxSize":"8g","freeSpacePercent":"5.0"}]'
  middleManagers:
    roleGroups:
      default:
        replicas: 1
        config:
          resources:
            cpu:
              min: "1"
              max: "4" # Need enough CPU cores to run multiple ingestion jobs at once
  routers:
    roleGroups:
      default:
        replicas: 1
```
During startup of a Druid with **default** settings the following log is shown
```
2023-01-19T15:38:14,891 INFO [main] org.apache.druid.guice.DruidProcessingModule - Unable to determine max direct memory size. If druid.processing.buffer.sizeBytes is explicitly configured, then make sure to set -XX:MaxDirectMemorySize to at least "druid.processing.buffer.sizeBytes * (druid.processing.numMergeBuffers[2] + druid.processing.numThreads[1] + 1)", or else set -XX:MaxDirectMemorySize to at least 25% of maximum jvm heap size.
2023-01-19T15:38:14,894 INFO [main] org.apache.druid.query.DruidProcessingConfig - Using up to [429,391,872] bytes of direct memory for computation buffers.
2023-01-19T15:38:14,894 INFO [main] org.apache.druid.query.DruidProcessingConfig - Auto sizing buffers to [107,347,968] bytes each for [1] processing and [2] merge buffers. If you run out of direct memory, you may need to set these parameters explicitly using the guidelines at https://druid.apache.org/docs/latest/operations/basic-cluster-tuning.html#processing-threads-buffers.
2023-01-19T15:38:14,895 INFO [main] org.apache.druid.offheap.OffheapBufferGenerator - Allocating new intermediate processing buffer[0] of size[107,347,968]
2023-01-19T15:38:15,078 INFO [main] org.apache.druid.guice.DruidProcessingModule - Unable to determine max direct memory size. If druid.processing.buffer.sizeBytes is explicitly configured, then make sure to set -XX:MaxDirectMemorySize to at least "druid.processing.buffer.sizeBytes * (druid.processing.numMergeBuffers[2] + druid.processing.numThreads[1] + 1)", or else set -XX:MaxDirectMemorySize to at least 25% of maximum jvm heap size.
2023-01-19T15:38:15,080 INFO [main] org.apache.druid.offheap.OffheapBufferGenerator - Allocating new result merging buffer[0] of size[107,347,968]
2023-01-19T15:38:15,137 INFO [main] org.apache.druid.offheap.OffheapBufferGenerator - Allocating new result merging buffer[1] of size[107,347,968]
2023-01-19T15:38:15,302 INFO [main] org.apache.druid.segment.loading.StorageLocation - SegmentLocation[/stackable/var/druid/segment-cache] will try and maintain [49107073433:982141468672] free space while loading segments.
```

**Comment by fhennig** [comment]
I've replicated the bug with this Druid config:

```
---
apiVersion: druid.stackable.tech/v1alpha1
kind: DruidCluster
metadata:
  name: simple-druid
spec:
  image:
    productVersion: 24.0.0
    stackableVersion: 0.3.0
  clusterConfig:
    deepStorage:
      hdfs:
        configMapName: simple-hdfs
        directory: /data
    metadataStorageDatabase:
      dbType: derby
      connString: jdbc:derby://localhost:1527/var/druid/metadata.db;create=true
      host: localhost
      port: 1527
    tls: null
    zookeeperConfigMapName: simple-druid-znode
  brokers:
    roleGroups:
      default:
        replicas: 1
  coordinators:
    roleGroups:
      default:
        replicas: 1
  historicals:
    roleGroups:
      default:
        replicas: 1
        config:
          resources:
            memory:
              limit: 4Gi
  middleManagers:
    roleGroups:
      default:
        replicas: 1
  routers:
    roleGroups:
      default:
        replicas: 1

```

- The crash doesn't happen for sizes < 1GB. 
- The limits on the STS Pod template are set correctly
- The crash only happens for the Historical, no other roles.

The error is `OutOfMemoryError: Direct buffer memory`. I think the historical is allocating stuff outside of the heap, and that might cause this problem. I'll investigate some settings.

**Comment by lfrancke** [comment]
There is one unchecked box above
@sbernauer I think you found this. Did you try this in the demo? Or did you @fhennig ?

**Comment by sbernauer** [comment]
I haven't tried it out in the demos, as the fix is not in 23.1.
I can offer to load-test a Druid and see if things are better now. But before I would continue on my current work of bumping the demos to 23.1

**Comment by fhennig** [comment]
I just saw my notification on this, I missed the box! Not sure how to proceed here, I'd really like to leave this to @sbernauer :grimacing:

**Comment by lfrancke** [comment]
Was this part of 23.1 or will it be in 23.4?

**Comment by maltesander** [comment]
I think it was after 23.1 so will be in 23.4.

**Comment by sbernauer** [comment]
It's in 23.4
We missed a changelog entry, created https://github.com/stackabletech/druid-operator/pull/400
