### ISSUE TITLE
Enable Log Aggregation for Druid

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/druid-operator#364]
See https://github.com/stackabletech/hbase-operator/issues/291 and https://github.com/stackabletech/docker-images/pull/283 for reference.

This is part of https://github.com/stackabletech/issues/issues/288

**Comment by maltesander** [comment]
It probably makes sense to wait here for
- https://github.com/stackabletech/druid-operator/pull/369
- https://github.com/stackabletech/druid-operator/pull/366
because of heavy CRD changes.
