### ISSUE TITLE
Implement authentication with LDAP secured via TLS

### ISSUE THREAD

**Issue by vsupalov** [stackabletech/druid-operator#382]
Related to https://github.com/stackabletech/druid-operator/issues/144

So far, non-TLS LDAP authentication was implemented. Adding ldaps:// support will involve adding certs provided for the LDAP server to the central trust store.

This task will probably involve modifying exising TLS-related code, and has been split out for clarity.

**Comment by lfrancke** [comment]
Do we have documentation for this?

**Comment by lfrancke** [comment]
@vsupalov ping
