### ISSUE TITLE
Authorize access to Druid

### ISSUE THREAD

**Issue by stefanigel** [stackabletech/druid-operator#4]
Authorize access to Druid by simple OPA RegoRules

**Acceptance Criteria** 
- [ ] It is checked if an individual implementation is needed or if we should use Ranger
- [ ] Druid OPA Authorizer is implemented (with or without Ranger)
- [ ] Druid Operator is able to write RegoRules

**Comment by lfrancke** [comment]
Sorry, I missed this and just created a new one: https://github.com/stackabletech/druid-operator/issues/145
