### ISSUE TITLE
Document how to load Druid extensions

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/druid-operator#487]
The documentation does not contain instructions on how to update the list of extensions that Druid should load upon startup. This can be done at the moment using configOverrides and adding the desired list of extensions to runtime.properties for each role.

An example of how this is done can be found in the OIDC kuttl test - https://github.com/stackabletech/druid-operator/blob/79b3eb38ed680b2a72ae63d935f36f84904957e1/tests/templates/kuttl/oidc/30-druid.yaml.j2

**Comment by fhennig** [comment]
Yeah it's annoying to do by hand, because you also need to list all the default extensions. I think it would be good to have an extra field for this, pinging @soenkeliebau because he worked on it before, maybe we can prioritize this higher? Should be easy to implement

**Comment by soenkeliebau** [comment]
I opened https://github.com/stackabletech/druid-operator/pull/416 but there were some discussions which I do not remember otomh..

**Comment by fhennig** [comment]
I created this larger epic about extensions in druid, which includes better default selection of extensions, better docs and better config ergonomics: https://github.com/stackabletech/druid-operator/issues/490

**Comment by fhennig** [comment]
This has now been documented: https://docs.stackable.tech/home/nightly/druid/usage-guide/extensions
