### ISSUE TITLE
Bootstrap an Apache Druid operator

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/druid-operator#5]
Implement initial Druid Operator for all Server-/Process Types (https://druid.apache.org/docs/latest/design/processes.html)  (ACs: )

**Acceptance Criteria**
- [x] Operator can start/stop/restart a Druid Cluster
- [x] Druid configs can be applied and updated
- [ ] Monitoring is integrated
- [ ] all Process types are supported (Coordinator, Overlord, Broker, Historical, MiddleManager and Peons, Indexer (Optional), Router (Optional)
- [ ] all  Server types are supported (Master, Query, Data)

- [ ] support Maturity Level 1 (Is there more todo than in AC 1?)

**tbd**
- [ ] ~~ships with license compatible JDBC driver for S3 (Does this really apply? Maybe not necessary (https://druid.apache.org/docs/latest/ingestion/native-batch.html#s3-input-source)~~

**Comment by fhennig** [comment]
The indexer was spun out into a seperate issue #8

**Comment by fhennig** [comment]
I've put the pod affinity in a seperate issue as well #9 , I believe the pod affinity is not critical to a minimal working version

**Comment by fhennig** [comment]
>  Druid configs can be applied and updated

a cluster config can be changed and with a restart the configs will be applied too
