### ISSUE TITLE
Package Druid

### ISSUE THREAD

**Issue by fhennig** [stackabletech/druid-operator#7]
I'd like [v0.22.0](https://druid.apache.org/downloads.html) packaged, together with a the [stackable startup script](https://github.com/stackabletech/druid-operator/blob/start/scripts/run-druid).

This is the directory structure that I'm working with right now:
```
        druid-0.22.0/
        └── apache-druid-0.22.0
            ├── bin
            ├── conf
            ├── lib
            ├── stackable/
                └── run-druid
            └── ...
```

**Comment by lfrancke** [comment]
This is done without the startup script and will be redundant after #11 anyway.
